markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: false
permalink: none
exclude: ["en-US/images/precompressed/", "node_modules", "Gruntfile.js", "package.json"]
url: http://designwithfontforge.com
title: Design With FontForge
title_ru-RU: Дизайн шрифта с FontForge
title_zh-CN: FontForge 与字体设计
title_zh-TW: FontForge 與字體設計
subtitle: A book about how to create new typefaces using FontForge
subtitle_ru-RU: Книга о создании новых шрифтов с помощью FontForge
subtitle_zh-CN: 介绍如何使用 FontForge 创造新字体的书
subtitle_zh-TW: 介紹以 FontForge 製作新字型的書
